### ISSUE TITLE
Add option to hide scroll bar

### ISSUE THREAD

**Issue by Gamer750** [SimpleMobileTools/Simple-Launcher#111]

**Comment by tibbi** [comment]
where, at the app drawer?

**Comment by Gamer750** [comment]
> where, at the app drawer?

![IMG_20230824_131026](https://github.com/SimpleMobileTools/Simple-Launcher/assets/141329708/f4b01016-20ab-496d-b07e-7b537f2d7a9e)

**Comment by tibbi** [comment]
that isnt on the roadmap, but we will change it to letters scrollbar soon

**Comment by Gamer750** [comment]
> that isnt on the roadmap, but we will change it to letters scrollbar soon

Just need a toggle button to hide
