### ISSUE TITLE
[Feature Request] Launcher without App Drawer.

### ISSUE THREAD

**Issue by Rexadev** [SimpleMobileTools/Simple-Launcher#12]
Add a mode where all apps are on home screen and there is not App Drawer.
Add ablity to group them into folders
Add ablity to multi-select Apps.

Something like `iOS` or `MIUI/Xiaomi`. There are a few apps that already do this like `Smart Launcher 5` (They removed the app and uploaded v6) and Fast Launcher.

**Comment by tibbi** [comment]
report things one by one please

**Comment by Rexadev** [comment]
@tibbi have a look now please
