### ISSUE TITLE
Sometimes app shortcuts are empty

### ISSUE THREAD

**Issue by ClockGen** [SimpleMobileTools/Simple-Launcher#132]
## Description
Sometimes app shortcuts don't have any text on them

## Screenshots
![Screenshot_20230921-100903_Launcher_1](https://github.com/SimpleMobileTools/Simple-Launcher/assets/12116711/cd3ee0e1-0d32-4b78-b067-1c00fec8c6a6)

## App version
5.1.0

## OS info
LineageOS 20 (Android 13)

**Comment by tibbi** [comment]
can you reproduce it reliably?
