### ISSUE TITLE
Please make like this instead of scrolling bottom to top

### ISSUE THREAD

**Issue by Gamer750** [SimpleMobileTools/Simple-Launcher#146]
![image](https://github.com/SimpleMobileTools/Simple-Launcher/assets/141329708/cf001e63-1432-4004-9a1d-d3c87169d6fe)

**Comment by tibbi** [comment]
you mean horizontal scrolling?

**Comment by Gamer750** [comment]
> you mean horizontal scrolling?

Yes

**Comment by tibbi** [comment]
actually duplicate of #21
