### ISSUE TITLE
Make Launcher Settings more discoverable

### ISSUE THREAD

**Issue by JohnVeness** [SimpleMobileTools/Simple-Launcher#155]
It took me an embarrassingly long time to find Launcher Settings! Maybe you could make it easier to find, for example, by putting it in the long-press desktop menu, and/or as an icon or an overflow menu in the app drawer search bar?

Version 5.1.1 from F-Droid.

**Comment by tibbi** [comment]
not really, this is the expected behaviour that works in other apps too. You can launch it from the device settings too.
