### ISSUE TITLE
Work profile apps: supported?

### ISSUE THREAD

**Issue by hiqua** [SimpleMobileTools/Simple-Launcher#164]
It's not clear to me whether work profile apps (enabled only when the work profile is enabled) are supposed to be supported, as the README does not mention them. If it's supported, I don't know how to access work apps when the profile is enabled.

Could you update the README to reflect this? I guess it's either:
* not supported and out of scope for this launcher
* not supported but PRs welcome
* supported and lacking some documentation

**Comment by tibbi** [comment]
nope, not supported and isnt really on the roadmap either
