### ISSUE TITLE
Weblate - Why there is empty string?

### ISSUE THREAD

**Issue by inson1** [SimpleMobileTools/Simple-Launcher#165]
![image](https://github.com/SimpleMobileTools/Simple-Launcher/assets/75314629/53731aa2-3951-4590-81fb-5f2bf59ca51a)

**Comment by tibbi** [comment]
not sure, might have been added by them

**Comment by inson1** [comment]
@tibbi By who? Did you delete the string?

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
