### ISSUE TITLE
Simple Launcher is the home screen

### ISSUE THREAD

**Issue by Pantyhose-X** [SimpleMobileTools/Simple-Launcher#168]
Is it possible to go directly back to Simple Launcher home screen.
* Simple Launcher is the home screen
* No more swiping up to get to Simple Launcher, or dragging icons to the home screen, no need to provide multiple screens.
![Screenshot_20240118-162531](https://github.com/SimpleMobileTools/Simple-Launcher/assets/42504385/d1bd00ef-8cd1-479e-b503-c24e68dc83ee)

* Maybe this is a separate feature, not the default.

**Comment by inson1** [comment]
@Pantyhose-X SMT apps were sold to ad company. https://github.com/SimpleMobileTools/General-Discussion/issues/241
Fork is here https://github.com/FossifyOrg

**Comment by Pantyhose-X** [comment]
> @Pantyhose-X SMT apps were sold to ad company. [SimpleMobileTools/General-Discussion#241](https://github.com/SimpleMobileTools/General-Discussion/issues/241) Fork is here https://github.com/FossifyOrg

I don't understand why they don't use Open Collective.

**Comment by inson1** [comment]
@Pantyhose-X Money wasnt the problem, https://github.com/SimpleMobileTools/General-Discussion/issues/241#issuecomment-1837452672

**Comment by Pantyhose-X** [comment]
> @Pantyhose-X Money wasnt the problem, [SimpleMobileTools/General-Discussion#241 (comment)](https://github.com/SimpleMobileTools/General-Discussion/issues/241#issuecomment-1837452672)
> 
> https://github.com/orgs/FossifyOrg/discussions/14

 We can migrate to https://postmarketos.org/  but we don't have the apps and games to meet people's needs.

**Comment by Pantyhose-X** [comment]
[7 Linux Smartphone Operating Systems to Install on Your Device](https://www.makeuseof.com/tag/linux-smartphone-operating-systems/) https://plasma-mobile.org/
