### ISSUE TITLE
[Suggestions] Folders in the app drawer / Horizontal mode / Additional layouts

### ISSUE THREAD

**Issue by WX4300** [SimpleMobileTools/Simple-Launcher#19]
1. Allow making folders (or/and) labels in the app drawer
2. Horizontal mode (I would use it mainly in a car but tablet users would appreciate it as well)
3. (If possible) i would love to be able to use more layouts in the future for example:
- Standard (the one you created just now)
- MIUI version
- iPhone version

We really like your apps and we wish you many successes 👍

**Comment by tibbi** [comment]
report things one by one please, unless they have been reported yet. Thanks
