### ISSUE TITLE
Some app icons missing

### ISSUE THREAD

**Issue by rudolfmu** [SimpleMobileTools/Simple-Launcher#24]
Some Apps have missing or no icon. The missing icons show when using Trebuchet or Samsung UI.
With Myphoneexplorer client the main icon shows, but the icons for notes, tasks and SMS are missing. With Trebuchet the main icon is missing, so there is no icon.

Device is Samsung A22 with Android 12.
Apps referenced:

https://play.google.com/store/apps/details?id=com.fjsoft.myphoneexplorer.client 

https://forum.xda-developers.com/t/app-port-lineageos-15-1-trebuchet-laucher-for-any-rom-ver-8-1-0-22.3667436/

**Comment by rudolfmu** [comment]
I did some further reviewing and noticed that Trebuchet having no icon is normal for Android 12. So Trebuchet is no issue.
The missing icons for Myphoneexplorer are not a feuture request. The app is not usable if you cannot click these.

**Comment by tibbi** [comment]
it is not a bug. The main app icon is ok, the missing icons are some extras.
