### ISSUE TITLE
Swipe up from bottom should close app drawer

### ISSUE THREAD

**Issue by firecat53** [SimpleMobileTools/Simple-Launcher#25]
Love the simplicity! Small usability comment: it seems like once you scroll up in the app drawer, the only way to close it is either a back gesture or by scrolling back up (swiping down) until the drawer closes. On the Pixel launcher, you can swipe up from the bottom at any point to close the drawer, just like closing any other app.

Thanks!

**Comment by tibbi** [comment]
that sounds weird, I dont plan adding that

**Comment by firecat53** [comment]
Hmm, it's exactly how the Pixel launcher app drawer works. Maybe I just described it poorly.

**Comment by tibbi** [comment]
maybe, I have 2 pixels and thats not how any of those works

**Comment by firecat53** [comment]
Heh, not a chance! I love my gesture navigation! 😉
