### ISSUE TITLE
[Feature Request] App drawer search

### ISSUE THREAD

**Issue by dallyger** [SimpleMobileTools/Simple-Launcher#34]
I would like to have the option to search through the app drawer to quickly find infrequently used apps without having to scroll through a long list trying to find it.
It would be nice too, if the keyboard automatically opens when accessing the drawer, so I can start typing immediately.
This may be a configurable option, as I guess, not everyone wants to use the search by default.

Anyway, thank you for your amazing work! This is another pleasant addition to your suite of apps.

**Comment by Alliba** [comment]
> I would like to have the option to search through the app drawer to quickly find infrequently used apps without having to scroll through a long list trying to find it. It would be nice too, if the keyboard automatically opens when accessing the drawer, so I can start typing immediately. This may be a configurable option, as I guess, not everyone wants to use the search by default.
> 
> Anyway, thank you for your amazing work! This is another pleasant addition to your suite of apps.

This function would be great.

**Comment by Pantyhose-X** [comment]
Hidden apps: Search should not show
Lend your phone to a friend or your kid at home, and you install some NSFW software 😰 so the hidden apps shouldn't be searched

**Comment by esensar** [comment]
Is this the same as #72? If so, it has been implemented in #81
