### ISSUE TITLE
[Feature Request] Layout Profiles

### ISSUE THREAD

**Issue by JustScott** [SimpleMobileTools/Simple-Launcher#42]
You could create multiple layout profiles, each allowing you to customize your home screen with apps and widgets.

For example you could have a work profile, which contains all your work related apps like LinkedIn & GitHub. Then have a personal profile which could contain apps like newpipe and random games.

If you really want to go all out, you could implement timers, which would automatically switch to your desired layout profile at a certain time you set.

**Comment by tibbi** [comment]
profiles arent really on the roadmap, that is way too advanced
