### ISSUE TITLE
[Bug] App crashes on startup

### ISSUE THREAD

**Issue by heschy2** [SimpleMobileTools/Simple-Launcher#56]
When I reboot my Phone (Samsung Galaxy S8 - Android 9) and log in, the Launcher does not start, and then two things happen:

1. I get the Message that Simple Launcher crashed (message by the android system)
2. I have to choose wich launcher i want to start now (oneui or simplelauncher) (message by the android system)

When I select Simple Launcher, the App starts and works perfectly.

It would be nice to remove this Bug, because it is pretty annoying,

**Comment by tibbi** [comment]
what app version are you using?

**Comment by tibbi** [comment]
will close this one, we are regularly fixing the most frequent crashes
