### ISSUE TITLE
App does not support android 6

### ISSUE THREAD

**Issue by Justauser0** [SimpleMobileTools/Simple-Launcher#69]

**Comment by tibbi** [comment]
it isnt on the roadmap

**Comment by Justauser0** [comment]
> it isnt on the roadmap

Why

**Comment by tibbi** [comment]
because barely anyone uses it already and some functions would be limited anyway

**Comment by Justauser0** [comment]
> because barely anyone uses it already and some functions would be limited anyway

Still!

**Comment by Gamer750** [comment]
> because barely anyone uses it already and some functions would be limited anyway

I also use android 6. Please make it compatible for android 6
