### ISSUE TITLE
Launcher is not properly working on notch

### ISSUE THREAD

**Issue by Justauser0** [SimpleMobileTools/Simple-Launcher#73]

**Comment by tibbi** [comment]
can you provide a screenshot of what you mean? What app and OS version are you using?

**Comment by Justauser0** [comment]
> can you provide a screenshot of what you mean? What app and OS version are you using?

![Screenshot_2023-07-10-12-36-50-47](https://github.com/SimpleMobileTools/Simple-Launcher/assets/135147872/f2d793e1-2387-4432-8ef4-a271e16ae5f9)

App Version 5.0.6

**Comment by tibbi** [comment]
what is the issue there? Notches cannot be seen on screenshots

**Comment by Justauser0** [comment]
> what is the issue there? Notches cannot be seen on screenshots

![IMG_20230720_083155](https://github.com/SimpleMobileTools/Simple-Launcher/assets/135147872/3e069302-7185-4baf-a777-c6c64e7473e7)

Other launcher

![Screenshot_2023-07-20-08-11-47-13](https://github.com/SimpleMobileTools/Simple-Launcher/assets/135147872/a0baccde-124c-4382-a55a-fd5836de7f65)
