### ISSUE TITLE
How to turn off vibration

### ISSUE THREAD

**Issue by Justauser0** [SimpleMobileTools/Simple-Launcher#91]

**Comment by tibbi** [comment]
where?

**Comment by Justauser0** [comment]
> where?



> where?

While moving apps in homescreen

**Comment by tibbi** [comment]
you cannot do it, not sure if I want a toggle for that..

**Comment by Justauser0** [comment]
> you cannot do it, not sure if I want a toggle for that..

If it had .It would be nice
